create table factions (
	states_name VARCHAR(14) primary key,
	faction_name VARCHAR(14)
);
insert into factions (states_name, faction_name) values ('Alabama', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Alaska', 'Carer College');
insert into factions (states_name, faction_name) values ('Arizona', 'The North Pets');
insert into factions (states_name, faction_name) values ('Arkansas', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('California', 'Carer College');
insert into factions (states_name, faction_name) values ('Colorado', 'Carer College');
insert into factions (states_name, faction_name) values ('Connecticut', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Delaware', 'Pets Landing');
insert into factions (states_name, faction_name) values ('Florida', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Georgia', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Hawaii', 'Carer College');
insert into factions (states_name, faction_name) values ('Idaho', 'Carer College');
insert into factions (states_name, faction_name) values ('Illinois', 'Carer College');
insert into factions (states_name, faction_name) values ('Indiana', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Iowa', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Kansas', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('Kentucky', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Louisiana', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Maine', 'Pets Landing');
insert into factions (states_name, faction_name) values ('Maryland', 'The North Pets');
insert into factions (states_name, faction_name) values ('Massachusetts', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('Michigan', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Minnesota', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('Mississippi', 'Pets Landing');
insert into factions (states_name, faction_name) values ('Missouri', 'The North Pets');
insert into factions (states_name, faction_name) values ('Montana', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Nebraska', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Nevada', 'The North Pets');
insert into factions (states_name, faction_name) values ('New Hampshire', 'The North Pets');
insert into factions (states_name, faction_name) values ('New Jersey', 'The North Pets');
insert into factions (states_name, faction_name) values ('New Mexico', 'Carer College');
insert into factions (states_name, faction_name) values ('New York', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('North Carolina', 'Carer College');
insert into factions (states_name, faction_name) values ('North Dakota', 'Carer College');
insert into factions (states_name, faction_name) values ('Ohio', 'The North Pets');
insert into factions (states_name, faction_name) values ('Oklahoma', 'Carer College');
insert into factions (states_name, faction_name) values ('Oregon', 'The North Pets');
insert into factions (states_name, faction_name) values ('Pennsylvania', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('Rhode Island', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('South Carolina', 'Carer College');
insert into factions (states_name, faction_name) values ('South Dakota', 'Pets Landing');
insert into factions (states_name, faction_name) values ('Tennessee', 'The North Pets');
insert into factions (states_name, faction_name) values ('Texas', 'The North Pets');
insert into factions (states_name, faction_name) values ('Utah', 'Fantastic Pets');
insert into factions (states_name, faction_name) values ('Vermont', 'Carer College');
insert into factions (states_name, faction_name) values ('Virginia', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('Washington', 'Carer College');
insert into factions (states_name, faction_name) values ('West Virginia', 'Pet Watchers');
insert into factions (states_name, faction_name) values ('Wisconsin', 'The North Pets');
insert into factions (states_name, faction_name) values ('Wyoming', 'Carer College');
